[workspace]
members = [
    "sighurt-browser",
    "sighurt-core",
    "sighurt-ui",
    "sighurt-engine-wasm",
    "sighurt-ipc",
    "sighurt-sdk",
    "examples/hello-sighurt",
    "examples/audio-player",
    "examples/raf-demo",
    "examples/timer-demo",
    "examples/fullstack-notes/frontend",
    "examples/fullstack-notes/backend",
    "examples/index",
    "examples/events-demo",
    "examples/gradient-demo",
    "examples/typography-demo",
    "examples/sse-demo",
]
exclude = ["sighurt-engine-servo"]
resolver = "2"
